size = 1000000000


# ---------------- LIST ----------------
memList:
	clear
	gcc lista/*.c -o prog
	valgrind ./prog $(size)

timeList:
	clear
	gcc lista/*.c -o prog
	./prog $(size)


# ---------------- VET ----------------
memVet:
	clear
	gcc vetor/*.c -o prog
	valgrind ./prog $(size)

timeVet:
	clear
	gcc vetor/*.c -o prog
	./prog $(size)






