size = 1000000000


# ---------------- LIST ----------------
compList:
	clear
	gcc lista/*.c -o prog

memList:
	clear
	gcc lista/*.c -o prog
	valgrind ./prog $(size)

timeList:
	clear
	gcc lista/*.c -o prog
	./prog $(size)


# ---------------- VET ----------------
compVet:
	clear
	gcc vetor/*.c -o prog

memVet:
	clear
	gcc vetor/*.c -o prog
	valgrind ./prog $(size)

timeVet:
	clear
	gcc vetor/*.c -o prog
	./prog $(size)






