#  path = "input/nearly_sorted/1000000.txt"
#  path = "input/reverse_sorted/1000000.txt"
  path = "input/sorted/1000000.txt"
#  path = "input/unif_rand/100000.txt"

m1:
	clear
	gcc client.c m1.c -o m1.ray
	./m1.ray $(path)

m2:
	clear
	gcc client.c m2.c -o m2.ray
	./m2.ray $(path)

m3:
	clear
	gcc client.c m3.c -o m3.ray
	./m3.ray $(path)

m4:
	clear
	gcc client.c m4.c -o m4.ray
	./m4.ray $(path)

m5:
	clear
	gcc client.c m5.c -o m5.ray
	./m5.ray $(path)

m6:
	clear
	gcc client.c m6.c -o m6.ray
	./m6.ray $(path)

m7:
	clear
	gcc client.c m7.c -o m7.ray
	./m7.ray $(path)

# clean
clean:
	clear
	rm -f *.o *.ray 