# ---------------- INT ----------------
memInt:
	clear
	gcc  tipos/int.c main.c -o prog
	valgrind ./prog

timeInt:
	clear
	gcc  tipos/int.c main.c -o prog
	./prog


# ---------------- CHAR ----------------
memChar:
	clear
	gcc  tipos/char.c main.c -o prog
	valgrind ./prog

timeChar:
	clear
	gcc  tipos/char.c main.c -o prog
	./prog


# ---------------- BIT ----------------
memBit:
	clear
	gcc tipos/bit.c tipos/bitmap.c main.c -o prog
	valgrind ./prog

timeBit:
	clear
	gcc tipos/bit.c tipos/bitmap.c main.c -o prog
	./prog







