# path = "in/few_uniq/10M_const_keys_sorted.txt"
# path = "in/few_uniq/10M_const_keys_unif_rand.txt"

# path = "in/nearly_sorted/100000.txt"
# path = "in/nearly_sorted/1000000.txt"
# path = "in/nearly_sorted/10000000.txt"

# path = "in/reverse_sorted/100000.txt"
# path = "in/reverse_sorted/1000000.txt"
# path = "in/reverse_sorted/10000000.txt"

# path = "in/sorted/100000.txt"
# path = "in/sorted/1000000.txt"
# path = "in/sorted/10000000.txt"

# path = "in/unif_rand/100000.txt"
# path = "in/unif_rand/1000000.txt"
 path = "in/unif_rand/10000000.txt"

q1:
	clear
	gcc client.c q1.c -o q1.ray
	./q1.ray $(path)

q2:
	clear
	gcc client.c q2.c -o q2.ray
	./q2.ray $(path)

q3:
	clear
	gcc client.c q3.c -o q3.ray
	./q3.ray $(path)

q4:
	clear
	gcc client.c q4.c -o q4.ray
	./q4.ray $(path)

q5:
	clear
	gcc client.c q5.c -o q5.ray
	./q5.ray $(path)

q6:
	clear
	gcc client.c q6.c -o q6.ray
	./q6.ray $(path)

q7:
	clear
	gcc client.c q7.c -o q7.ray
	./q7.ray $(path)

q8:
	clear
	gcc client.c q8.c -o q8.ray
	./q8.ray $(path)

q9:
	clear
	gcc client.c q9.c -o q9.ray
	./q9.ray $(path)

# clean
clean:
	clear
	rm -f *.ray 